version: "3.7"
services:
  admin-frontend:
    build: 
      context: ./client/admin
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./client/admin:/admin-frontend
    depends_on:
      - porvenir-db
    networks:
      - porvenir-net
  web-server:
    container_name: porvenir-server
    build: ./server
    ports:
      - "8282:8282"
    environment:
      DATABASE_URL: postgres://admin:admin123!@porvenir-db:5432/porvenir
      ENV: dev
    volumes:
      - /Users/alexventura/go/pkg/mod:/go/pkg/mod
    command: /server
    depends_on:
      - porvenir-db
    networks:
      - porvenir-net
  porvenir-db:
    image: postgres:12
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123!
      - POSTGRES_DB=porvenir
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - porvenir-net
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123!
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - porvenir-db
    ports:
      - 5050:5050/tcp
    networks:
      - porvenir-net
    restart: unless-stopped
    tty: true
volumes: 
  database_data:

networks: 
  porvenir-net:
    driver: bridge