// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type User struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type IncomeType string

const (
	IncomeTypeOwnBusiness            IncomeType = "OWN_BUSINESS"
	IncomeTypeOnwEmployee            IncomeType = "ONW_EMPLOYEE"
	IncomeTypePrivateCompanyEmployee IncomeType = "PRIVATE_COMPANY_EMPLOYEE"
	IncomeTypePublicEmployee         IncomeType = "PUBLIC_EMPLOYEE"
)

var AllIncomeType = []IncomeType{
	IncomeTypeOwnBusiness,
	IncomeTypeOnwEmployee,
	IncomeTypePrivateCompanyEmployee,
	IncomeTypePublicEmployee,
}

func (e IncomeType) IsValid() bool {
	switch e {
	case IncomeTypeOwnBusiness, IncomeTypeOnwEmployee, IncomeTypePrivateCompanyEmployee, IncomeTypePublicEmployee:
		return true
	}
	return false
}

func (e IncomeType) String() string {
	return string(e)
}

func (e *IncomeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncomeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncomeType", str)
	}
	return nil
}

func (e IncomeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OnboardingStatus string

const (
	OnboardingStatusComplete            OnboardingStatus = "COMPLETE"
	OnboardingStatusPendingPersonalData OnboardingStatus = "PENDING_PERSONAL_DATA"
	OnboardingStatusPendingCiFront      OnboardingStatus = "PENDING_CI_FRONT"
	OnboardingStatusPendingCiBack       OnboardingStatus = "PENDING_CI_BACK"
	OnboardingStatusPendingPhoneNumber  OnboardingStatus = "PENDING_PHONE_NUMBER"
)

var AllOnboardingStatus = []OnboardingStatus{
	OnboardingStatusComplete,
	OnboardingStatusPendingPersonalData,
	OnboardingStatusPendingCiFront,
	OnboardingStatusPendingCiBack,
	OnboardingStatusPendingPhoneNumber,
}

func (e OnboardingStatus) IsValid() bool {
	switch e {
	case OnboardingStatusComplete, OnboardingStatusPendingPersonalData, OnboardingStatusPendingCiFront, OnboardingStatusPendingCiBack, OnboardingStatusPendingPhoneNumber:
		return true
	}
	return false
}

func (e OnboardingStatus) String() string {
	return string(e)
}

func (e *OnboardingStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OnboardingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OnboardingStatus", str)
	}
	return nil
}

func (e OnboardingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
